### ISSUE TITLE
Signin from IDEA takes us to a Android Studio Page

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/gcloud-intellij#146]
![signin 2015-10-20 10 17 32](https://cloud.githubusercontent.com/assets/1005544/10609959/e7c20a66-7713-11e5-8862-9d170d4ab4df.png)

**Comment by patflynn** [comment]
+kmckormick
+csells

Aha!  Good point!  That needs to be fixed ASAP.

This ties into the documentation issue we have been discussing. We don't
really have much landing page content to provide on auth success for
IntelliJ users.

Katie and Chris, what do you guys think about creating a barebones landing
page in the interim?

**Comment by patflynn** [comment]
This takes us right onto the slippery slope, doesn't it?

I'm not sure what in the IDE triggers the display of these specific pages.
Do you guys know what the mechanism is?

This definitely needs to be addressed, but it's not obvious what the right
solution is. Chris, what are your thoughts?

Katie

**Comment by patflynn** [comment]
As you point out, Katie, we’ll need a set of CT4IJ docs on c.g.com <http://c.g.com/> just like the CT4AS docs. However, while we figure that out, can we just get a IntelliJ-specific page for login?

**Comment by patflynn** [comment]
>
However, while we figure that out, can we just get a IntelliJ-specific page
for login?
>

Instead of creating an IntelliJ directory on cloudsite when we might be
hosting IntelliJ content on github, why not change the behavior of IntelliJ
to do something other than display the Android Studio page?

The Android Studio is just an HTML page
<https://cs.corp.google.com/#piper///depot/google3/googledata/devsite/site-cloud/en/tools/android-studio/auth_success.html>.
It doesn't have any special magic. I don't know how IntelliJ is invoking
it, but I don't see any particular advantage to IntelliJ opening a page on
cloudsite at this point.

Katie

**Comment by patflynn** [comment]
++Rajeev and Jared

We’re pretty sure that we want to host our product docs on c.g.com <http://c.g.com/>, although we’re still haggling about whether we keep the source of the docs in github.
