### ISSUE TITLE
Make TOS notification support internationalization

### ISSUE THREAD

**Issue by nbashirbello** [GoogleCloudPlatform/gcloud-intellij#177]
The notification for TOS contains hyperlinks. In UsageTrackerNotification, make these links support internationalization.

**Comment by elharo** [comment]
You're asking about these 4 string constants, right?

                    if ("allow".equals(description)) {
                    else if ("decline".equals(description)) { 
                    else if ("policy".equals(description)) {
                    else if ("settings".equals(description)) {


This matches up to 

notification.popup.content=<html>Please click <a href='allow'>I agree</a> if you want to help make Google IntelliJ plugins better or <a href='decline'>I don't agree</a> otherwise. <a href='settings'>Settings...</a></html>";

in UsageTrackerBundle.properties

**Comment by elharo** [comment]
annoyingly nested properties are not supported:

http://stackoverflow.com/questions/28181970/does-java-util-properties-support-nested-properties

**Comment by elharo** [comment]
These are not actually user-visible strings so they don't need to be internationalized.
