### ISSUE TITLE
Cloud Repo checkout hides key fields when parent directory is modified

### ISSUE THREAD

**Issue by patflynn** [GoogleCloudPlatform/gcloud-intellij#249]
![screenshot from 2015-12-01 16 29 51](https://cloud.githubusercontent.com/assets/7862557/11514900/f2c9f67a-9848-11e5-9ca8-d4477da1bfef.png)

Steps:
1) Start IJ with the CT plugin installed
2) Checkout project from Cloud Repos
3) login and pick a project
4) modify the parent project path

observe that the UI for the project directory disappears.

**Comment by patflynn** [comment]
Hey @joaoandremartins, do you want to try this one out?

**Comment by elharo** [comment]
Ans on top  that the Clone from Google Cloud dialog isn't wide enough for the message it needs to contain.

**Comment by elharo** [comment]
This is com.google.gct.idea.git.CloneGcpDialog

**Comment by elharo** [comment]
And there's a missing colon after "Cloud Project" label

**Comment by joaoandremartins** [comment]
@patflynn sorry I missed this, my notifications must be turned off.

Yeah, will take a stab.

**Comment by joaoandremartins** [comment]
@patflynn is this still happening to you? If so, do you have more precise instructions on how to reproduce?

Using ./gradlew runIdea (IDEA 15.0.1 Community Edition), selecting a project from the drop down and writing on the parent project box doesn't do anything. Selecting an existing folder also doesn't do anything.

**Comment by patflynn** [comment]
@joaoandremartins I'm not seeing it anymore. It appears that the issue was caused by the validation error that the directory name already exists.  For some reason when I try to reproduce it now puts enough vertical space not to hide the fields.   As @elharo pointed out the horizontal space is still not enough to fully display the validation error which needs to be fixed.

**Comment by joaoandremartins** [comment]
I can see two ways to resolve this issue: to dynamically resize the window as the user inputs text or to select a fixed size for the window and highlight the project directory field in red.

I prefer the second approach since the first one has a few corner cases (e.g., user pastes directory, variable char length, too big a message causes multiple error lines, low res screens, window dynamically expanding is bad user experience, etc.).

What do you think?

**Comment by elharo** [comment]
I'm not sure what you mean here. I don't think the user inputs text directly in this dialog. I think now it dynamically resizes to fit the width of the longest name in the Cloud Project dropdown, but I'd have to check. 

The simplest thing that could possibly work might be to make it 50-70% bigger min width and add one extra line's worth of vertical size too. 

If you're feeling ambitious, you could try to figure out how to let the path string break on the path separator character (/ on Linux)

**Comment by joaoandremartins** [comment]
The "Parent directory" text box is fillable by users and the error text echoes the parent directory.

I really feel like the best approach is to not echo the directory in the error message, make the window a bit larger and highlight the Parent directory text box in red. I'll give this one a go and see how it turns out.

**Comment by elharo** [comment]
That sounds like a good idea.
