### ISSUE TITLE
Avoid flashing in Attach dialog

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/gcloud-intellij#309]
When the below dialog pops up it often flashes through several variations with different error labels before settling down to the final state shown here.

![image](https://cloud.githubusercontent.com/assets/1005544/11720779/da15e6c4-9f2e-11e5-907a-eef7549924ba.png)

In particular:

1. "Please select a module" (in red) is shown and then vanishes.
2. The left button is initially a disabled "Attach" button instead of the "Continue Session" button shown here.

This is distracting to the user. I suspect we're loading the modules asynchronously, and once they come in we change the widgets we show.

We should try to figure out what the state will be sooner so the dialog doesn't flash like that.

**Comment by patflynn** [comment]
There should be a loading state with a clear visual indicator.

**Comment by etanshaul** [comment]
It seems elharo is correct that the modules are being loaded asynchronously leading to this issue:

The combobox is currently being populated by a separate thread (see ProjectDebuggeeBinding.refreshDebugTargetList). Furthermore, the since dialog validation happens via a timer, it *may* happen that validation occurs on a fully displayed dialog with the combobox still unpopulated - in this case the error message will display until the data gets loaded and the next validation cycle occurs.  This explains the current non-deterministic behavior where the flashing message only occurs sometimes.

Looking into a fix.

**Comment by patflynn** [comment]
awesome. Thanks for the update.

**Comment by etanshaul** [comment]
The dialog class (and our GUI classes in general) is proving hard to unit test without significant refactoring outside the scope of this issue. Either we undertake the necessary refactoring as we encounter these issues to improve test coverage, or we separate this effort into separate issue(s). 

Any thoughts on approaches to handle these scenarios?

**Comment by patflynn** [comment]
I don't think there's a hard and fast rule.  You have some luxury of time
right now, so if you want to undertake the refactoring work, please do so.
Although send out a doc or mail explaining the issue, and how you want to
address it first.  Otherwise do what you can, don't make things worse, and
file a refactoring issue, that we can prioritize against our other work.
