### ISSUE TITLE
We need to include plugin version in our feedback reports and ideally our user-agent

### ISSUE THREAD

**Issue by patflynn** [GoogleCloudPlatform/gcloud-intellij#333]
I don't know that this information is available yet at runtime. Should be packaged into our plugin.

**Comment by joaoandremartins** [comment]
@patflynn Do you want the HTTP User-Agent? Or do you just want to know which FeedbackSender implementation was used to send the feedback [1]?

I understand that we can't get the User-Agent from Google Feedback, but it can be a little tricky to get it on the client. It is possible, but if we want to know how the feedback's being sent, I think we can just send a FeedbackSender ID along with the message.

[1] https://github.com/GoogleCloudPlatform/gcloud-intellij/blob/master/common-lib/src/main/java/com/google/gct/idea/feedback/GoogleAnonymousFeedbackTask.java

**Comment by patflynn** [comment]
This issue is poorly worded.  It's really two issues.  One is getting our version into our user-agent for RPC calls to GCP services, the other is reporting our current version is a dimension in the google feedback error report.

**Comment by joaoandremartins** [comment]
I added the plugin version to the feedback's Product Specific Data section.

<img width="399" alt="screen shot 2016-01-22 at 4 13 11 pm" src="https://cloud.githubusercontent.com/assets/3290856/12523211/541e57d8-c123-11e5-9bc8-4602772bb73a.png">

In order to read it, we need to go to Feedback and click the Show PII button in a report. For now, it doesn't come in the emails, but this might just need tuning some setting in the Feedback side to include PSD there. I can talk to the Feedback team about this.

As for adding our version to the User-Agent header, we're using the Google API client libraries that I'm not sure support this, but will take a look. Do we have a list of GCP APIs we're consuming anywhere? That would be helpful.

**Comment by patflynn** [comment]
Let's chat about this offline. I'm not 100% following this.
