### ISSUE TITLE
We should test CDB behavior for a multi-module GAE1 application.

### ISSUE THREAD

**Issue by patflynn** [GoogleCloudPlatform/gcloud-intellij#363]

**Comment by patflynn** [comment]
I'm curious what the module selector will look like on attach.

**Comment by etanshaul** [comment]
I just tested this on a sample multi-module app: https://github.com/GoogleCloudPlatform/appengine-modules-sample-java

Here is what the CDB dialog looks like:

![image](https://cloud.githubusercontent.com/assets/1735744/12627080/e230d430-c509-11e5-85d9-91b1a0da4a67.png)

Notices that both modules are labeled "Version: 1"

The web UI shows the following:

![image](https://cloud.githubusercontent.com/assets/1735744/12628821/11578822-c513-11e5-9cd8-32c233598a80.png)

It shows 2 modules: "default" and "shardedcounter". We probably want to update the plugin to display the module name rather than the version in the module selector.

This also brings up another question: our IJ UI only shows one level - "modules". In reality, there are multiple abstractions here: "modules" at the top, and each module can have multiple "versions". Do we want to adapt our UI to account for this?  At first we could simply have the latest version be the implicitly selected one. See https://cloud.google.com/appengine/docs/java/modules/ for more info about modules and versions.

**Comment by etanshaul** [comment]
This requires further investigation. The screenshots I shared above are from the App Engine page in the web UI. The Debug page (web ui), on the other hand, does not split the project into modules. 

It is currently unclear to me what those 2 different "Version: 1" labels that are returned from the API to our plugin actually represent. There is no module name being returned by the API for us to use.

**Comment by etanshaul** [comment]
Here is the corresponding view of this project from the Web UI Debug page:

![image](https://cloud.githubusercontent.com/assets/1735744/12659739/58103fae-c5de-11e5-9f79-d04e5cf544ef.png)

Notice only a single "default" module in the selector, as well as a consolidated view of the entire project in the source browser.
