### ISSUE TITLE
"Retake the snapshot" button in Developers Console causes duplicate breakpoint in IDEA

### ISSUE THREAD

**Issue by joaoandremartins** [GoogleCloudPlatform/gcloud-intellij#382]
And then, when the breakpoints are hit, they're hit simultaneously.

We're probably not keeping track of breakpoint's IDs properly.

**Comment by joaoandremartins** [comment]
The action of adding and removing a snapshot itself creates duplicates in IDEA.

**Comment by akerekes** [comment]
This is currently the expected behavior, because the Dev Console creates a new snapshot location each time the button is clicked and when the IDEA plugin queries the results from the Cloud Debugger, it will return all breakpoints including seemingly duplicates. We could filter out breakpoints that have the same properties (creation time would not be considered when checking for equality) and display only one of them (the most recently created one).
