### ISSUE TITLE
We should make our plugin compatible with the IJ 16 EAP.

### ISSUE THREAD

**Issue by patflynn** [GoogleCloudPlatform/gcloud-intellij#438]
This should hopefully be as simple as changing the gradle-intellij-plugin config.

**Comment by etanshaul** [comment]
I just tested it out and we already are compatible:

I configured the gradle-intellij-plugin to target version IC-144.3891.8 (EAP 16) then built the plugin. Did a few smoke tests and it ran without issue. I did have to initially build the plugin and launch idea via the command line first to get it working (gradlew buildPlugin; gradlew runIdea) - probably due to gradle / idea caches.

So it looks like there is nothing to do here. There is a newer version of the gradle-intellij-plugin plugin but thats for a different PR.

**Comment by etanshaul** [comment]
I'm assuming here we want to continue developing against 15 until 16 comes out of EAP.

**Comment by patflynn** [comment]
That's right.  Let's set the version to target 15 and up for now.

**Comment by etanshaul** [comment]
Due to limitations with the gradle-intellij-plugin we currently would need 2 releases to achieve this:
1) To support 15.0 and up - we need to set ideaVersion to 15.0, and cut a release.
2) To support EAP 16 - we would need to cut another release with the version updated again.

There is no way to specify a version "X and up" where X spans a major version using the gradle-intellij-plugin plugin (this is because it doesn't allow specifying a "since" version _without_ an "until"). 

There is an issue filed against this plugin to make it more robust: https://github.com/JetBrains/gradle-intellij-plugin/issues/66
