### ISSUE TITLE
Managed VM Cloud configs should clearly state the financial costs of deployment

### ISSUE THREAD

**Issue by patflynn** [GoogleCloudPlatform/gcloud-intellij#452]
Unlike regular App Engine deployments Managed VM deployments typically spin up multiple VMs which do not scale down to 0.  Additionally multiple deployments create multiple running versions which can quickly add up to significant costs for the user.  

It's critical that when the user creates a Managed VM Cloud deployment target that we have clear messaging in the UI what the costs are.

**Comment by etanshaul** [comment]
Suggesting solution:

I can create an info label on the Cloud Deployment dialog (the dialog the user sees right before executing a deploy) explaining that multiple deploys will create multiple versions together with a link to the app engine pricing page: https://cloud.google.com/appengine/pricing

**Comment by etanshaul** [comment]
Also, since #453 is related to this and somewhat depends on how we solve this, I'll put forward this approach for #453:

Next to the info label that I previously suggested, there will be some sort of button ("Manage running instances") which will expand open a scrollable area listing all the user's running modules / versions. Next to each line item the user will be able to click a stop button/icon to stop the instance.

**Comment by etanshaul** [comment]
Approach discussed offline with @patflynn:

Add info label with link to pricing page as described. For stopping instances, tie into the "undeploy" UI that shows up in the Application Server panel after a successful deploy (right click menu and sidebar icon).

**Comment by etanshaul** [comment]
Closing this issue based on offline discussion.

**Comment by patflynn** [comment]
We absolutely need some kind of wording. Let's discuss offline.
