### ISSUE TITLE
strange label for an artifact being deployed using mvm

### ISSUE THREAD

**Issue by patflynn** [GoogleCloudPlatform/gcloud-intellij#526]
When deploying a filesystem jar/war using mvm the 'Application Server' UI shows the artifact up as 'userSpecfiedSource' instead of the deployment filename. 

![screenshot from 2016-03-23 14 53 01](https://cloud.githubusercontent.com/assets/7862557/13997135/fa2edbda-f106-11e5-951e-78b337231639.png)

**Comment by etanshaul** [comment]
Adding steps to reproduce since this is a tricky one:

1) Create a cloud deployment source
2) Select a file system archive to deploy, and run
3) Close and re-open the ide (there may be another way without this step)
4) In the app server window right click on the cloud you created and try to deploy to the same deployment source

**Comment by chanseokoh** [comment]
This one is a bit tricky. 'userSpecifiedSource' is a name given to a ModulePointer obj when it's created. It's supposed to be immutable and gets serialized into an XML. On the other hand, 'Filesystem JAR or WAR file - <actual file>' is what @etanshaul just sets as a presentable name on-the-fly and seems not being serialized and restored.

The name 'userSpecifiedSource' is used as a unique key to a hash map, so I don't think it's a good idea to change the name. I could change it with a hacky way that fixes this bug, but it's somewhat dirty and I don't think it's the right solution.

The simplest solution would be a compromise to always use a name 'Filesystem JAR or WAR file' without an actual file name, but that will be a last resort.

**Comment by chanseokoh** [comment]
When the IDE starts up, it will de-serialize a source deployment configuration using the method below:

com.intellij.remoteServer.impl.configuration.deployment.ModuleDeploymentSource.load()

It will create the normal 'ModuleDeploymentSourceImpl' during the process. However, we extended that class in order to have a mutable presentable name. So, we need to create our extended 'UserSpecifiedPathDeploymentSource' and do proper initialization during 'load()' if we want to make it work cleanly. I'm not yet familiar with plugin-in development, so @etanshaul, you have some idea how I can hook into this 'load()' method to have my own 'load()' executed during IDE start-up?
