### ISSUE TITLE
App Engine deploy should support cancelling the deployment

### ISSUE THREAD

**Issue by patflynn** [GoogleCloudPlatform/gcloud-intellij#581]

**Comment by meltsufin** [comment]
+1

**Comment by meltsufin** [comment]
This is potentially related to #588.

**Comment by etanshaul** [comment]
Adding note from discussion with @meltsufin:

If #588 ties in stopping the deployment to the disconnect method of the ServerRuntimeInstance (and hence to the UI button), then that would somewhat resolve this issue: the user could kill the in progress deployment by hitting the disconnect button. 

This is slightly less than ideal because the disconnect acts at the cloud level acting on all of its deployments. Also, the user would have to know to click on the cloud to do the disconnect since the button is not available when the deployment is selected. We need to investigate if there are ways to do this at the deployment level.

**Comment by patflynn** [comment]
I've noticed that this is how IntelliJ's app engine cloud integration works
too.

**Comment by meltsufin** [comment]
Check [this help page](https://www.jetbrains.com/help/idea/2016.1/application-servers-tool-window.html?origin=old_help) out from IntelliJ. Apparently, server artifacts can have a "Remove" icon on the toolbar.
