### ISSUE TITLE
Make deployment version part of main configuration

### ISSUE THREAD

**Issue by meltsufin** [GoogleCloudPlatform/gcloud-intellij#639]
The user should be able to easily override the default version configuration without having to specify app.yaml and Dockerfile. Version configuration should also be given more prominence by moving it outside of the "Custom Configuration" panel.

![deployment_config](https://cloud.githubusercontent.com/assets/17732492/14609606/907f24c2-0558-11e6-80c5-241dae9f1a3c.png)

**Comment by chanseokoh** [comment]
Since the version field is grayed out and auto-generated by default, I agree on moving it out to the outer panel.

**Comment by etanshaul** [comment]
:+1 there's no reason a user should be forced to override app.yaml / Dockerfile in order to specify a version. 

The other solution (besides moving version out of the custom configuration) is to also make the specification of app.yaml / Dockerfile toggleable (something like the override checkbox). This way we just have basic configuration that is shown by default to the user (which the majority will use), with the option to show advanced configuration.

**Comment by meltsufin** [comment]
I like the idea of making app.yaml / Dockerfile selection and the Version, individually toggleable. In that case, we can get rid of the whole Auto / Custom drop-down and make all options always visible. They can still be placed into an "Advanced" section.

**Comment by chanseokoh** [comment]
Makes sense. This can lead to a lot of changes in the UI and code, so I suggest we make a solid design before taking an action.

**Comment by patflynn** [comment]
I'm not sure app.yaml and Dockerfile should be individually togglable. I
think there's a certain amount of coupling between the Dockerfile and the
app.yaml for now.
