### ISSUE TITLE
Missing SDK for maven deploys should be more user friendly

### ISSUE THREAD

**Issue by etanshaul** [GoogleCloudPlatform/gcloud-intellij#774]
Currently if the user attempts to deploy a maven source to app engine flex without an SDK being configured for the project, this message is shown:

![image](https://cloud.githubusercontent.com/assets/1735744/16671314/bccfeb08-446c-11e6-8ff8-59df96766012.png)
This isn't a clickable link even though it looks like markup.

On the other hand, if the user deploys a native IJ artifact source to flex they see this:

![image](https://cloud.githubusercontent.com/assets/1735744/16671277/90760a42-446c-11e6-93d8-9954c5ce66f1.png)
Clicking on 'ok' takes the user to the settings page to select an SDK which is much nicer.

**Comment by etanshaul** [comment]
I noticed that when trying to run a maven goal from the maven panel in the ide without an sdk setup, the user is shown the following:

![image](https://cloud.githubusercontent.com/assets/1735744/16700807/dcf115e8-4529-11e6-85d7-0342aaf7037e.png)

This also much better than what is happening now. So its possible that the maven build task that occurs during deploy can be configured somehow to show the message in a better way.

**Comment by joaoandremartins** [comment]
The issue seems to be contained in IDEA's code. This also happens when you run a Maven task with Before launch tasks on an SDK-less project.

https://github.com/JetBrains/intellij-community/blob/10a4c91dbfca935b4b5531003fd8c13b56e66202/plugins/maven/src/main/java/org/jetbrains/idea/maven/execution/MavenExternalParameters.java#L343

I opened an issue on YouTrack. https://youtrack.jetbrains.com/issue/IDEA-158773
