### ISSUE TITLE
Update local run/debug to use the common library

### ISSUE THREAD

**Issue by etanshaul** [GoogleCloudPlatform/gcloud-intellij#782]

**Comment by joaoandremartins** [comment]
@etanshaul as discussed, going to take over this. Feel free to assign other existing similar issues on the run/debug with commlib to me!

**Comment by joaoandremartins** [comment]
Currently, running an app locally is very tightly coupled with running a Java process (because in any other way, e.g., an API call, the debugger can't work).

So, for this work, my suggestion is to first change all SDK location mechanisms to be performed using the library and, on a second stage, change the Java process run into an API call (if possible).

**Comment by etanshaul** [comment]
The CloudSdk builder has a callback (startListener) which gives the running process. I wonder if this can be used? Check out AppEngineRunner#run() to see how I'm using it for deploy.

**Comment by etanshaul** [comment]
Also regarding the changing of the SDK locations - I'm also working on #787 and #781 which are tightly coupled to each other, and to this. 

So we may want to coordinate a plan - my approach currently is to keep all the old SDK (appcfg) code as is, deprecate it, and move the new gcloud SDK code alongside it. After that is done, and after all consumers use the gcloud sdk, we can remove the deprecated appcfg code.

**Comment by joaoandremartins** [comment]
The current implementation with `AppEngineServerConfigurationType` relies on `JavaCommandLineStartupPolicy` to run code on start and shutdown, and to run a Java process with arguments given by us.

The whole IDEA framework seems to be geared towards Run/Debug Configurations only running processes, whereas we only want to make a library call.

http://www.jetbrains.org/intellij/sdk/docs/basics/run_configurations/run_configuration_execution.html

Because the com.intellij.javaee framework appears to be limited in functionality and severely lacks documentation, I'm going to give it a shot at creating a new Run/Debug Configuration for devappserver, with a ProgramRunner that only calls the library.

**Comment by patflynn** [comment]
@joaoandremartins should this be linked to your last PR?
