### ISSUE TITLE
Deploying a standard app using Maven module as deployment src from Community Edition fails

### ISSUE THREAD

**Issue by patflynn** [GoogleCloudPlatform/gcloud-intellij#820]
Steps to reproduce:

1) Create a Maven based AE standard app
2) Import into IntelliJ CE
3) Do a Maven build (I think there's another bug I need to file here if you try and deploy without ever having done a build)
4) Notice that it thinks the app is 'app engine flexible'
5) do a deployment
6) Notice that it tries to stage the App Engine packaged war as a standard Java archive and do a flex deployment.

Expected outcome:

1) deployment config would show it as a standard app
2) deployment would be turned off or be smart enough to deploy it somehow.

**Comment by etanshaul** [comment]
Just noting that I am unable to reproduce the bug hinted at by #3: the deployment correctly kicks off a maven build even its the first time for a freshly cloned maven ae standard project.

Proposed solution I will explore: if the user opens an AE standard app in CE, then the deployment window will show an error (even if all fields are properly configured) indicating that UE must be used for an AE standard app.

Actual deployment within CE is something we should explore in the future in a different PR.

**Comment by etanshaul** [comment]
There are some changes that need to go in to address this issue for UE too. Currently, if an AE standard project is opened up in Ultimate but the user doesn't configure the GAE framework as shown in the screenshot then the AE standard facet does not get applied:

![image](https://cloud.githubusercontent.com/assets/1735744/17861325/9a32e940-685e-11e6-972d-1eacd894f7a1.png)

Then attempting to deploy this project gives the following deployment window. Note that it recognizes it as 'flexible' and so the issue now is identical to the CE issue:

![image](https://cloud.githubusercontent.com/assets/1735744/17861356/b3d0c1ba-685e-11e6-96fc-ab59170e8224.png)

So a similar thing needs to be done for UE too - it should be recognized as a 'standard' project, but _not_ deployable - with wording indicating that the framework needs to be configured (ideally with a link if possible).

**Comment by patflynn** [comment]
I'm starting to wonder if we should couple the deployment strategy to the facet.  I don't like the idea of having to duplicate the logic of determining whether a module is standard or not, but perhaps the fact that a user hasn't configured a facet shouldn't determine the way we detect and deploy an application.

**Comment by etanshaul** [comment]
Where is the duplication you refer to? There wouldn't be any duplication between CE and UE. One approach I could take is adding an `isDeployableToAppEngineStandard` method to the `AppEngineDeployableInterface`. It would be hardcoded to false for the clearly non AE standard source, and for the ones that could go either way, it would be determined at creation time.

**Comment by etanshaul** [comment]
After offline discussion with @patflynn and more thinking about this, here are my current thoughts:

- We will _not_ get rid of the AE standard facet. This is a good place to add UI for things like configuring libs.
  - Deployment will no longer be tied to the presence of the AE framework (and therefore the facet). If a user attempts to deploy an app engine standard project without having configured the framework / facet, this should still work - deployment is currently only dependent on an SDK which was moved out of the facet. In order to make this work we will need a deployment-config-time check to see if the project is an AE standard project.
- If attempting to deploy an AE standard app with no viable deployment source - e.g. in CE with no exploded-war types - the user will be shown an error message and deployment will be disabled (in a future PR we can add support for maven based standard apps). This behavior is distinctly different than what currently happens where in this case we just assume its a flex deployment.

@patflynn, @joaoandremartins - what do you guys think of this plan?

**Comment by patflynn** [comment]
Sounds good.  You mention removing the SDK config from the Facet. I thought
it was at the application level anyway.  Do you mean just removing the UI
that passes through to the application level config?

**Comment by etanshaul** [comment]
I meant that the SDK was already removed from the facet. There is no longer any UI on the facet level for configuring the SDK.

**Comment by joaoandremartins** [comment]
If we're deploying standard apps as flex apps, because we can't deploy them as standard, I agree we should stop this. I would be very surprised to see it happening as a user, and just spinning up flex instances might incur in more costs than if standard instances were spun up.

I don't know what to think about declaring libraries at the facet level. On one hand, there is already the Libraries screen where, theoretically, that should be handled. On the other hand, as a user, I think it's more intuitive to specify which App Engine libs I want to select from an App Engine screen, rather than a generic Libraries one, but I might be isolated here.
Apart from specifying libs, I don't see any other use for a facet. Could we use it to proxy appengine-web.xml settings like app ID, version, etc?

**Comment by etanshaul** [comment]
@joaoandremartins regarding your lib point: I see the facet as a good place to create a more user friendly UI for configuring the libs. Rather than automatically adding everything, or having the user manually browse to jars, the facet could expose a UI that allows them to select what they want (similarly to how it currently works for the soon-to-be-removed datanucleus stuff).

I'm not sure at the moment what else we'd want to use the facet for, but I anticipate using it more in the future. But regardless I don't think its a good idea to remove it altogether.

**Comment by joaoandremartins** [comment]
Yes, I agree with you. I actually think we could use the facet as a way to configure an App Engine app settings management (https://cloud.google.com/appengine/docs/java/config/appref), if I'm not misunderstanding what facets should be used for.

**Comment by patflynn** [comment]
I think that's exactly what they're for.  Good idea.

**Comment by etanshaul** [comment]
That's not a bad idea. But it would get a little hairy though having both the appengine-web.xml and the these facet settings.

**Comment by joaoandremartins** [comment]
The way I see it, the facet would serialize on appengine-web.xml. We could maybe even reuse the same UI for the facet and deployment, where I think you're already specifying some deployment settings.

**Comment by etanshaul** [comment]
Ah yea. Having the facet and appengine-web.xml synced would be really nice. It solves the pain of having to write xml with a nice UI.

**Comment by etanshaul** [comment]
An update to the plan for this that I outlined previously. Specifically dealing with this point:

> If attempting to deploy an AE standard app with no viable deployment source - e.g. in CE with no exploded-war types - the user will be shown an error message and deployment will be disabled (in a future PR we can add support for maven based standard apps). This behavior is distinctly different than what currently happens where in this case we just assume its a flex deployment.

Because of limitations with the way IJ handles the deployment panel for cases with no deployment sources - specifically it doesn't show any custom panel and gives us no opportunity for showing error messages - I am leaning towards just having an empty deployment panel for this scenario (clicking run will pop up a generic error saying no deployment source was selected):

![image](https://cloud.githubusercontent.com/assets/1735744/18066796/ed9df292-6e07-11e6-9d47-90e2ccaf71b1.png)


The alternative would be to create a dummy deployment source just for the sake of being able to show an error message to the user. However, this doesn't feel clean to me and there is no way to visually mark the deployment source with red text (or something similar).

**Comment by patflynn** [comment]
I think this is fine in the context of us providing better support shortly
after.
