### ISSUE TITLE
Was not notified of conflicting AE plugin

### ISSUE THREAD

**Issue by etanshaul** [GoogleCloudPlatform/gcloud-intellij#865]
Steps:

- Install the latest version of IntelliJ UE
- Enable the latest release of the cloud tools plugin - notice that the old JB plugin is enabled
- Open an AE standard project (e.g. https://github.com/loosebazooka/simple-appengine-app)

Expected to see a plugin conflict warning, but none was shown. 

@aslo do you mind taking a look?

**Comment by aslo** [comment]
I was under the impression that the changes from https://github.com/GoogleCloudPlatform/gcloud-intellij/pull/803 have not been released yet, since they are part of the integration work for the 1.0-beta release. 

This was the commit made to master when that PR was merged: https://github.com/GoogleCloudPlatform/gcloud-intellij/commit/31e5d527de4b0fe6bb53c94b25193cb7dacf1d11. I verified that it's not an ancestor of the most recent release by running the following command (where a non-zero status code signals that the first commit is not an ancestor of the second):
```
$ git merge-base --is-ancestor 31e5d527de4b0fe6bb53c94b25193cb7dacf1d11 v0.9.7.5-beta ; echo $?
1
```

You should, however see those features in master.

**Comment by etanshaul** [comment]
ahhhh yea you're right. sorry..wasn't thinking straight there for a minute.
